name: Zip and Release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'New release version'
        required: true
        type: string
        
env:
  MOD_VERSION: ${{ github.event.inputs.release_tag }}
  
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        lfs: 'true' 
    - name: Update ModInfo.xml
      run: sed -i "s|<Version value=\"[^\"]*\" />|<Version value=\"{${{ env.MOD_VERSION }}}\" />|" Mods/AgeOfOblivion/ModInfo.xml
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'AgeOfOblivion.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: create release
      uses: ading2210/gh-large-releases@v1
      with:
        draft: true
        files: 'AgeOfOblivion.zip'
        tag_name: "${{ env.MOD_VERSION }}"
